#!/bin/sh

where=$1 || ./src
tests=$1
if [ -d $where ]; then
  tests=`find $where -type f -name '*-test.*' -not -path './node_modules/*'`
fi

`npm bin`/istanbul cover `npm bin`/_mocha -- --compilers js:babel/register --recursive $tests
